server {
    listen 80;
    server_name localhost;

    # 1. FRONTEND
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. DJANGO ADMIN
    location /admin/ {
        proxy_pass http://django:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. STATIC FILES (CSS/JS cho Admin)
    location /static/ {
        proxy_pass http://django:8000/static/;
    }

    # 4. DJANGO APIs
    location ~ ^/api/(login|register|user|logout)/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 5. .NET APIs
    location ~ ^/api/(Hoadon|Sanpham|Donhang)/ {
        proxy_pass http://dotnet:7132;
        proxy_set_header Host $host;
    }

    # 6. Fallback
    location /api/ {
        proxy_pass http://django:8000;
    }
}