events {}

http {
    server {
        listen 80;

        # Django
        location /api/chat/ {
            proxy_pass http://django:8000;
        }

        # .NET
        location /api/Hoadon {
            proxy_pass http://dotnet:7132;
        }
    }
}