server {
    listen 80;
    server_name localhost;

    # 1. FRONTEND
   # nginx/nginx.conf
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;

        # TẮT CACHE ĐỂ CODE CẬP NHẬT TỨC THÌ
        sendfile off;
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;
    }

    # 2. DJANGO ADMIN
    location /admin/ {
        proxy_pass http://django:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. STATIC FILES (CSS/JS cho Admin)
    location /static/ {
        proxy_pass http://django:8000/static/;
    }

    # 4. DJANGO APIs
    location ~ ^/api/(login|register|user|reset-password|reset-password-cofirm)/ {
        proxy_pass http://django:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 5. .NET APIs
    location ~ ^/api/(Hoadon|Sanpham|Donhang)/ {
        proxy_pass http://dotnet:7132;
        proxy_set_header Host $host;
    }

    # 6. Fallback
    location /api/ {
        proxy_pass http://django:8000;
    }
}