"""
Django settings for django_service project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import importlib.util
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import pymysql
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))
pymysql.install_as_MySQLdb()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8080')

ALLOWED_HOSTS = ['*']
SOCIALACCOUNT_LOGIN_ON_GET = True
CORS_ALLOW_ALL_ORIGINS = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
LOGIN_REDIRECT_URL = '/api/oauth/google/success/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'EMAIL_AUTHENTICATION': True,
        'VERIFIED_EMAIL': True,
    }
}
# Application definition

INSTALLED_APPS = [
    "unfold",
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'corsheaders',
    'rest_framework',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'django_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'django_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''), 
        'HOST': os.environ.get('DB_HOST', 'mysql_db'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'api.User'

SIMPLE_JWT = {
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SECRET"),
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}

UNFOLD = {
    "SITE_TITLE": "Veggie Admin",
    "SITE_HEADER": "Veggie Store",
    "SITE_SUBHEADER": "Bảng quản trị vận hành Veggie Store",
    "SITE_SYMBOL": "eco",
    "SITE_URL": FRONTEND_URL,
    "SITE_DROPDOWN": [
        {
            "icon": "storefront",
            "title": "Mở website",
            "link": FRONTEND_URL,
            "attrs": {
                "target": "_blank",
                "rel": "noopener noreferrer",
            },
        },
        {
            "icon": "contact_mail",
            "title": "Hộp thư liên hệ",
            "link": reverse_lazy("admin:api_contact_changelist"),
        },
    ],
    "SHOW_HISTORY": True,
    "DASHBOARD_CALLBACK": "api.admin.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "#effcf6",
            "100": "#d9f7e8",
            "200": "#b8efd3",
            "300": "#8ddfb5",
            "400": "#57c88c",
            "500": "#2fab68",
            "600": "#1f8f63",
            "700": "#176d4b",
            "800": "#15543b",
            "900": "#123b2e",
            "950": "#092118",
        },
    },
    "SIDEBAR": {
    "show_search": True,
    "show_all_applications": True,
    "navigation": [

        # ================= TỔNG QUAN =================
        {
            "title": "Tổng quan",
            "separator": True,
            "items": [
                {
                    "title": "Dashboard",
                    "icon": "dashboard",
                    "link": reverse_lazy("admin:index"),
                },
                {
                    "title": "Liên hệ khách hàng",
                    "icon": "support_agent",
                    "link": reverse_lazy("admin:api_contact_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_contact"),
                },
            ],
        },

        # ================= CUNG CẤP =================
        {
            "title": "Cung cấp",
            "separator": True,
            "items": [
                {
                    "title": "Nhà Cung Cấp",
                    "icon": "local_shipping",
                    "link": reverse_lazy("admin:api_supplier_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_supplier"),
                },
                {
                    "title": "Phiếu nhập",
                    "icon": "assignment_return",
                    "link": reverse_lazy("admin:api_entryform_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_entryform"),
                },
                {
                    "title": "Chi tiết phiếu nhập",
                    "icon": "list_alt",
                    "link": reverse_lazy("admin:api_entryformdetail_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_entryformdetail"),
                }
            ]
        },

        # ================= GIẢM GIÁ =================
        {
            "title": "Giảm giá",
            "separator": True,
            "items": [
                {
                    "title": "Voucher",
                    "icon": "card_giftcard",
                    "link": reverse_lazy("admin:api_voucher_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_voucher"),
                },
                {
                    "title": "Người sử dụng",
                    "icon": "how_to_reg",
                    "link": reverse_lazy("admin:api_uservoucher_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_uservoucher"),
                }
            ]
        },

        # ================= DANH MỤC =================
        {
            "title": "Danh mục",
            "separator": True,
            "items": [
                {
                    "title": "Sản phẩm",
                    "icon": "inventory",
                    "link": reverse_lazy("admin:api_product_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_product"),
                },
                {
                    "title": "Danh mục sản phẩm",
                    "icon": "category",
                    "link": reverse_lazy("admin:api_category_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_category"),
                },
                {
                    "title": "Ảnh sản phẩm",
                    "icon": "photo",
                    "link": reverse_lazy("admin:api_productimage_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_productimage"),
                },
            ],
        },

        # ================= BÁN HÀNG =================
        {
            "title": "Bán hàng",
            "separator": True,
            "items": [
                {
                    "title": "Đơn hàng",
                    "icon": "receipt",
                    "link": reverse_lazy("admin:api_order_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_order"),
                },
                {
                    "title": "Chi tiết đơn",
                    "icon": "shopping_cart",
                    "link": reverse_lazy("admin:api_orderitem_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_orderitem"),
                },
            ],
        },

        # ================= TÀI KHOẢN =================
        {
            "title": "Tài khoản",
            "separator": True,
            "items": [
                {
                    "title": "Người dùng",
                    "icon": "person",
                    "link": reverse_lazy("admin:api_user_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_user"),
                },
                {
                    "title": "Vai trò",
                    "icon": "admin_panel_settings",
                    "link": reverse_lazy("admin:api_role_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_role"),
                },
                {
                    "title": "Phân quyền",
                    "icon": "lock",
                    "link": reverse_lazy("admin:api_permission_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_permission"),
                },
            ],
        },

        # ================= HỦY =================
        {
            "title": "Hủy",
            "separator": True,
            "items": [
                {
                    "title": "Phiếu hủy",
                    "icon": "cancel",
                    "link": reverse_lazy("admin:api_cancelform_changelist"),
                    "permission": lambda request: request.user.has_perm("api.view_cancelform"),
                },
            ],
        },
    ],
}
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# email 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# GHN
GHN_TOKEN = os.getenv('GHN_TOKEN')
GHN_SHOP_ID = os.getenv('GHN_SHOP_ID')
GHN_API_URL = os.getenv('GHN_API_URL')


# REDIS

REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1")

if importlib.util.find_spec("django_redis") and REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "veggie-local-cache",
        }
    }
