# Generated by Django 4.2.18 on 2026-04-21 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_gram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='created_user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_entry_forms', to=settings.AUTH_USER_MODEL),
        ),
    ]
