# Generated by Django 4.2 on 2026-03-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đã xác nhận'), (3, 'Đang giao'), (4, 'Đã giao'), (5, 'Đã hủy'), (6, 'Hoàn trả')], default=1),
        ),
    ]
