# Generated by Django 4.2 on 2026-04-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_created_at_contact_reply_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='district_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ward_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
