# Generated by Django 4.2.18 on 2026-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_weight_gram_alter_entryform_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('done', 'DONE')], default='draft', max_length=50),
        ),
    ]
