# Generated by Django 4.2.18 on 2026-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shippingaddress_district_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
