# Generated by Django 4.2.18 on 2026-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_average_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoucher',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
