# Generated by Django 4.2.18 on 2026-04-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_entryform_status'),
        ('api', '0004_alter_uservoucher_used_at'),
    ]

    operations = [
    ]
