# Generated by Django 4.2.18 on 2026-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20260428_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
    ]
